# Generated by Django 5.1.3 on 2024-12-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='equipment_feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
