# Generated by Django 5.1.3 on 2024-12-03 07:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authkit', '0007_user_batch'),
        ('classroom', '0002_alter_feedback_equipment_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookings',
        ),
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedbacks',
        ),
        migrations.RenameModel(
            old_name='Classroom',
            new_name='Rooms',
        ),
    ]
