# Generated by Django 5.1.3 on 2024-12-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_rename_booking_bookings_rename_feedback_feedbacks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_hoc_booking',
            field=models.BooleanField(default=False),
        ),
    ]
