# Generated by Django 5.1.3 on 2024-12-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_bookings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='marker_count',
            field=models.IntegerField(default=0),
        ),
    ]
