# Generated by Django 5.1.3 on 2024-12-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authkit', '0002_user_profile_picture_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Faculty', 'Faculty')], max_length=255, null=True),
        ),
    ]
